### PR TITLE
Jp articles

### PR DESCRIPTION
**Pull request by JohnDPrice**
## What is it?
- This component contains an article list that displays a list of cards containing the article title, url, and synopsis. The articles are sorted by date in descending order and each card has an edit and delete button. The articles displayed in the DOM are only for the user currently logged in.

## How to test it
- Test this component by registering as a user and logging in. Click the "Articles" link in the navbar and then click the "Add new article" button at the top of the page. You will be presented with a form that allows you to input the article title, URL, and synopsis. After you save the article it will be given a time stamp that allows us to sort the articles. After clicking the "Save" button you should see the article appear in the DOM. Repeat this several times to see how the articles are sorted in descending order by date. To test the delete functionality, add a new article and then click the "Release Article" button on the card.

### CODE REVIEW

**Comment by angela-therese** [comment]
Works as described. Good job!

**Comment by MandyC6420** [comment]
**Nutshell QA Review of**: Ticket #3 Shared news articles

**Description of bug found**: 
When adding a new article for the first time
click on add new article
A second Articles H1 Heading and a second Add New Article button is included above the article
jparticlesspidereye



**Console Logs**(if any):

**Steps to reproduce defect**: 
Pleases select add new article
once form is displayed
view along bottom to find another option to add a new article that doesn't function upon button click

**Expected Vs.  Actual results**:
Expected to add article without seeing a second affordance while doing so

All other features such as add, edit, and release work perfectly.  Please take this advice and continue with your project

**Comment by JohnDPrice** [comment]
> **Nutshell QA Review of**: Ticket #3 Shared news articles
> 
> **Description of bug found**:
> When adding a new article for the first time
> click on add new article
> A second Articles H1 Heading and a second Add New Article button is included above the article
> jparticlesspidereye
> 
> **Console Logs**(if any):
> 
> **Steps to reproduce defect**:
> Pleases select add new article
> once form is displayed
> view along bottom to find another option to add a new article that doesn't function upon button click
> 
> **Expected Vs. Actual results**:
> Expected to add article without seeing a second affordance while doing so
> 
> All other features such as add, edit, and release work perfectly. Please take this advice and continue with your project

I had the form displaying on its own page with nothing else displaying in the DOM except the form but Tommy said the form should display above the ArticleList

**Comment by MandyC6420** [comment]
The functionality of the this branch is wonderful.  I would continue on with your work as expected.  This is just a visual feature :)

**Comment by JohnDPrice** [comment]
> The functionality of the this branch is wonderful. I would continue on with your work as expected. This is just a visual feature :)

Okay thanks, I thought it made more sense to do it the way you're suggesting I just changed it because Tommy's suggestion to have it display on the same page.

**Pull request closed without merging**
